import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://crmuat.cylsys.com/');
  await page.pause();
  await page.getByRole('textbox', { name: 'Enter email' }).click();
  await page.getByRole('textbox', { name: 'Enter email' }).fill('sudhanshu.mishra@cylsys.com');
  await page.getByRole('textbox', { name: 'Enter email' }).press('Tab');
  await page.locator('#PasswordVal').fill('123456789');
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.getByRole('button', { name: 'Reports' }).click();
  await page.getByRole('link', { name: 'Email Log Report' }).click();
  await page.getByLabel('From Date:').fill('2024-10-11');
  await page.getByLabel('To Date:').fill('2024-12-03');
  await page.getByRole('button', { name: 'Search' }).click();
  // const downloadPromise = page.waitForEvent('download');
  // await page.getByRole('button', { name: '' }).click();
  // const download = await downloadPromise;
  await page.getByRole('link', { name: 'Contact' }).click();
  await page.goto('https://crmuat.cylsys.com/Contact/AllContact');
  await page.getByRole('button', { name: 'Sudhanshu mishra' }).click();
  await page.getByRole('button', { name: ' Setting' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByPlaceholder('MobileNo').click();
  await page.getByPlaceholder('MobileNo').fill('9027522127');
  await page.getByRole('link', { name: 'Update' }).click();
  await page.getByText('Something went wrong. Please').click();
  await page.getByRole('button', { name: 'Sudhanshu mishra' }).click();
  await page.getByRole('button', { name: ' Change Password' }).click();
  await page.getByPlaceholder('Current Password').click();
  await page.getByPlaceholder('Current Password').fill('123456789');
  await page.getByPlaceholder('New Password').click();
  await page.getByPlaceholder('New Password').fill('123456789');
  await page.getByPlaceholder('Confirm Password').click();
  await page.getByPlaceholder('Confirm Password').fill('123456789');
  await page.getByRole('link', { name: 'Submit' }).click();
  await page.getByText('Something went wrong. Please').click();
  await page.getByRole('button', { name: 'Sudhanshu mishra' }).click();
  await page.getByRole('button', { name: ' Logout' }).click();
  await page.goto('https://crmuat.cylsys.com/');
});