import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AcMMx-fQl2T1RQlPowDnhS8TFS7yBIHPRsK5ipSnzjr2aHRiTv6716KLLe-APNJ2YY8UmpKw-4LfxA&osid=1&passive=1209600&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-1861499514%3A1733512994964764&ddm=1');
  await page.getByRole('button', { name: 'Create account' }).click();
  await page.getByText('For my personal use').click();
  await page.getByLabel('First name').fill('teena');
  await page.getByLabel('Last name (optional)').click();
  await page.getByLabel('Last name (optional)').fill('yadav');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Month').selectOption('6');
  await page.getByLabel('Day').click();
  await page.getByLabel('Day').fill('22');
  await page.getByLabel('Year').click();
  await page.getByLabel('Year').fill('2000');
  await page.getByLabel('Gender', { exact: true }).selectOption('2');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('teeeeeeeenaaaaaaaa23');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'ty605603' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Password', { exact: true }).fill('12345678');
  await page.getByLabel('Confirm').click();
  await page.getByLabel('Confirm').fill('12345678');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Please choose a stronger').click();
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('Test@11122');
  await page.getByLabel('Confirm').click();
  await page.getByLabel('Confirm').fill('test@11122');
  await page.getByLabel('Show password').check();
  await page.getByLabel('Confirm').click();
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').press('ArrowLeft');
  await page.getByLabel('Confirm').fill('Test@11122');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Phone number').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Please enter a phone number').click();
  await page.getByLabel('Phone number').click();
  await page.getByLabel('Phone number').fill('987656789');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('This phone number format is').click();
  await page.getByLabel('Phone number').click();
  await page.getByLabel('Phone number').fill('9876567890');
  await page.getByRole('button', { name: 'Next' }).click();
});